
version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: inventory-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventorydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: inventory-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    # Uncomment if you want to see SQL in logs
    # environment:
    #   SPRING_JPA_SHOW_SQL: "true"

volumes:
  pgdata:
